# Generated by Django 4.2.8 on 2023-12-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_carousel_carousel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
