# Generated by Django 4.2.8 on 2023-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_carousel_sub_title_carousel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_title', models.CharField(max_length=300)),
                ('charity_desc', models.TextField()),
                ('mission_title', models.CharField(max_length=300)),
                ('mission_desc', models.TextField()),
                ('vision_title', models.CharField(max_length=300)),
                ('vision_desc', models.TextField()),
            ],
        ),
    ]
