# Generated by Django 4.2.8 on 2023-12-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mission_vision_rename_charity_desc_about_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='image1',
            field=models.FileField(blank=True, max_length=300, upload_to='mission/'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='image2',
            field=models.FileField(blank=True, max_length=300, upload_to='mission/'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='image1',
            field=models.FileField(blank=True, max_length=300, upload_to='vision/'),
        ),
        migrations.AlterField(
            model_name='vision',
            name='image2',
            field=models.FileField(blank=True, max_length=300, upload_to='vision/'),
        ),
    ]
