# Generated by Django 4.2.8 on 2023-12-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_mission_image1_alter_mission_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Causes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=300)),
                ('main_sub_title', models.CharField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('fund_raised', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='causes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='mission',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='vision',
            name='image2',
        ),
    ]
