# Generated by Django 4.2.8 on 2023-12-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_causes_remove_mission_image2_remove_vision_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causes',
            name='main_sub_title',
        ),
        migrations.RemoveField(
            model_name='causes',
            name='main_title',
        ),
    ]
