# Generated by Django 4.2.8 on 2023-12-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_causes_main_sub_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('designation', models.CharField(blank=True, max_length=300)),
                ('image', models.FileField(blank=True, max_length=600, upload_to='')),
            ],
        ),
    ]
