# Generated by Django 4.2.8 on 2023-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.FileField(blank=True, max_length=600, upload_to='team/'),
        ),
    ]
