# Generated by Django 4.2.8 on 2023-12-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Causes',
        ),
    ]
