# Generated by Django 4.2.8 on 2023-12-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_team_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('account', models.CharField(blank=True, max_length=40)),
                ('ifsc_code', models.CharField(blank=True, max_length=40)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
