# Generated by Django 4.2.8 on 2023-12-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='qrcode',
            field=models.FileField(blank=True, max_length=500, upload_to='qrcode/'),
        ),
        migrations.AddField(
            model_name='donate',
            name='upi_id',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
