# Generated by Django 4.2.8 on 2023-12-24 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 24, 9, 27, 1, 945641, tzinfo=datetime.timezone.utc)),
        ),
    ]
