# Generated by Django 4.2.8 on 2023-12-27 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 10, 48, 0, 769229, tzinfo=datetime.timezone.utc)),
        ),
    ]
