# Generated by Django 4.2.8 on 2023-12-27 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 27, 13, 20, 32, 402589, tzinfo=datetime.timezone.utc)),
        ),
    ]
